### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by tomoya0827** [tomoya0827/protospace-39671#1]
#URL
https://protospace-39671.onrender.com/

**Comment by mo1015** [comment]
@tomoya0827 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプ名をクリックした場合に遷移しないため修正しましょう。

- [x] **正しくプロトタイプが編集できた場合は、プロトタイプ詳細ページへ遷移すること**
トップページへ遷移してしまいます。

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
プロトタイプ詳細ページの投稿者名をクリックした場合に遷移しません。（トップページへ遷移してしまいます）

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
どちらもトップページへ遷移してしまいます。ログインページにリダイレクトされるよう修正しましょう。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーのプロトタイプ編集ページへ遷移できてしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tomoya0827** [comment]
ご指摘の箇所修正いたしました。本番環境でも動作確認致しましたので、ご確認お願いいたします。

**Comment by motomuun** [comment]
@tomoya0827 さん、再度ご提出頂きありがとうございます‼︎
動作の確認をしたところ、一点だけ修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ一覧表示機能**

- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプ名をクリックすると、「ユーザーの」詳細ページへ遷移します。「プロトタイプの」詳細ページへ遷移するように修正をお願いします。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tomoya0827** [comment]
該当箇所の修正が終わりました。お手数ですがご確認をお願いいたします。

**Comment by yusuketono** [comment]
@tomoya0827 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
